name: Build and Publish Electron.NET App

on:
  push:
    branches:
      - main  # Change this to your release branch if necessary

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Output Run Attempt
      run: echo ${{ github.run_number }}

    - name: get Version
      run:  echo "BUILD_VERSION_UPDATE=1.0.${{ github.run_number }}" >> $GITHUB_ENV
      shell: bash

    - name: set client version
      run: 'sed -i "s|\"buildVersion\": \".*\"|\"buildVersion\": \"$BUILD_VERSION_UPDATE\"|g" electron.manifest.json'
      shell: bash

    - name: Install Electron.NET CLI
      run: dotnet tool install --global ElectronNET.CLI

    - name: Publish Electron.NET to Windows
      run: electronize build /target win

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: bin/Desktop/*.exe # forward slashes MUST be used here, otherwise no artifacts will be found
        tag_name: ${{ env.BUILD_VERSION_UPDATE }}
